name: TfSec Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tfsec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16'

      - name: Install TfSec
        run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: Run TfSec
        run: tfsec .